// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgdkn6h5ih_oGKaPqll-1Om8ZWu4SBsts',
    appId: '1:175581322528:web:c3a3cb913490c9625f0b45',
    messagingSenderId: '175581322528',
    projectId: 'new-chat-app-39f78',
    authDomain: 'new-chat-app-39f78.firebaseapp.com',
    storageBucket: 'new-chat-app-39f78.appspot.com',
    measurementId: 'G-43GX33ZQTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9Trs8pqM15aIWB3cFxbaKNFjsWi-VmQ',
    appId: '1:175581322528:android:6ba9347d878b7f7d5f0b45',
    messagingSenderId: '175581322528',
    projectId: 'new-chat-app-39f78',
    storageBucket: 'new-chat-app-39f78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQt-qMLbglt0o2umuzxJ3L1S7dr_jMxk',
    appId: '1:175581322528:ios:823493f72c2941b65f0b45',
    messagingSenderId: '175581322528',
    projectId: 'new-chat-app-39f78',
    storageBucket: 'new-chat-app-39f78.appspot.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDQt-qMLbglt0o2umuzxJ3L1S7dr_jMxk',
    appId: '1:175581322528:ios:2a59e0e77b2b4f8a5f0b45',
    messagingSenderId: '175581322528',
    projectId: 'new-chat-app-39f78',
    storageBucket: 'new-chat-app-39f78.appspot.com',
    iosBundleId: 'com.example.newChatApp.RunnerTests',
  );
}
